// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/game_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conference int32

const (
	Conference_CONFERENCE_UNSPECIFIED Conference = 0
	Conference_CONFERENCE_AFC         Conference = 1
	Conference_CONFERENCE_NFC         Conference = 2
)

// Enum value maps for Conference.
var (
	Conference_name = map[int32]string{
		0: "CONFERENCE_UNSPECIFIED",
		1: "CONFERENCE_AFC",
		2: "CONFERENCE_NFC",
	}
	Conference_value = map[string]int32{
		"CONFERENCE_UNSPECIFIED": 0,
		"CONFERENCE_AFC":         1,
		"CONFERENCE_NFC":         2,
	}
)

func (x Conference) Enum() *Conference {
	p := new(Conference)
	*p = x
	return p
}

func (x Conference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Conference) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_service_proto_enumTypes[0].Descriptor()
}

func (Conference) Type() protoreflect.EnumType {
	return &file_proto_game_service_proto_enumTypes[0]
}

func (x Conference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Conference.Descriptor instead.
func (Conference) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{0}
}

type Division int32

const (
	Division_DIVISION_UNSPECIFIED Division = 0
	Division_DIVISION_AFC_EAST    Division = 1
	Division_DIVISION_AFC_NORTH   Division = 2
	Division_DIVISION_AFC_SOUTH   Division = 3
	Division_DIVISION_AFC_WEST    Division = 4
	Division_DIVISION_NFC_EAST    Division = 5
	Division_DIVISION_NFC_NORTH   Division = 6
	Division_DIVISION_NFC_SOUTH   Division = 7
	Division_DIVISION_NFC_WEST    Division = 8
)

// Enum value maps for Division.
var (
	Division_name = map[int32]string{
		0: "DIVISION_UNSPECIFIED",
		1: "DIVISION_AFC_EAST",
		2: "DIVISION_AFC_NORTH",
		3: "DIVISION_AFC_SOUTH",
		4: "DIVISION_AFC_WEST",
		5: "DIVISION_NFC_EAST",
		6: "DIVISION_NFC_NORTH",
		7: "DIVISION_NFC_SOUTH",
		8: "DIVISION_NFC_WEST",
	}
	Division_value = map[string]int32{
		"DIVISION_UNSPECIFIED": 0,
		"DIVISION_AFC_EAST":    1,
		"DIVISION_AFC_NORTH":   2,
		"DIVISION_AFC_SOUTH":   3,
		"DIVISION_AFC_WEST":    4,
		"DIVISION_NFC_EAST":    5,
		"DIVISION_NFC_NORTH":   6,
		"DIVISION_NFC_SOUTH":   7,
		"DIVISION_NFC_WEST":    8,
	}
)

func (x Division) Enum() *Division {
	p := new(Division)
	*p = x
	return p
}

func (x Division) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Division) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_service_proto_enumTypes[1].Descriptor()
}

func (Division) Type() protoreflect.EnumType {
	return &file_proto_game_service_proto_enumTypes[1]
}

func (x Division) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Division.Descriptor instead.
func (Division) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{1}
}

type GameStatus int32

const (
	GameStatus_GAME_STATUS_UNSPECIFIED GameStatus = 0
	GameStatus_GAME_STATUS_SCHEDULED   GameStatus = 1
	GameStatus_GAME_STATUS_IN_PROGRESS GameStatus = 2
	GameStatus_GAME_STATUS_COMPLETED   GameStatus = 3
	GameStatus_GAME_STATUS_POSTPONED   GameStatus = 4
	GameStatus_GAME_STATUS_CANCELED    GameStatus = 5
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "GAME_STATUS_UNSPECIFIED",
		1: "GAME_STATUS_SCHEDULED",
		2: "GAME_STATUS_IN_PROGRESS",
		3: "GAME_STATUS_COMPLETED",
		4: "GAME_STATUS_POSTPONED",
		5: "GAME_STATUS_CANCELED",
	}
	GameStatus_value = map[string]int32{
		"GAME_STATUS_UNSPECIFIED": 0,
		"GAME_STATUS_SCHEDULED":   1,
		"GAME_STATUS_IN_PROGRESS": 2,
		"GAME_STATUS_COMPLETED":   3,
		"GAME_STATUS_POSTPONED":   4,
		"GAME_STATUS_CANCELED":    5,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_service_proto_enumTypes[2].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_proto_game_service_proto_enumTypes[2]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{2}
}

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Abbreviation  string                 `protobuf:"bytes,4,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	Conference    Conference             `protobuf:"varint,5,opt,name=conference,proto3,enum=proto.Conference" json:"conference,omitempty"`
	Division      Division               `protobuf:"varint,6,opt,name=division,proto3,enum=proto.Division" json:"division,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Stadium       string                 `protobuf:"bytes,8,opt,name=stadium,proto3" json:"stadium,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_proto_game_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{0}
}

func (x *Team) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Team) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

func (x *Team) GetConference() Conference {
	if x != nil {
		return x.Conference
	}
	return Conference_CONFERENCE_UNSPECIFIED
}

func (x *Team) GetDivision() Division {
	if x != nil {
		return x.Division
	}
	return Division_DIVISION_UNSPECIFIED
}

func (x *Team) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *Team) GetStadium() string {
	if x != nil {
		return x.Stadium
	}
	return ""
}

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HomeTeamId    string                 `protobuf:"bytes,2,opt,name=home_team_id,json=homeTeamId,proto3" json:"home_team_id,omitempty"`
	AwayTeamId    string                 `protobuf:"bytes,3,opt,name=away_team_id,json=awayTeamId,proto3" json:"away_team_id,omitempty"`
	Week          int32                  `protobuf:"varint,4,opt,name=week,proto3" json:"week,omitempty"`
	Status        GameStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=proto.GameStatus" json:"status,omitempty"`
	HomeScore     int32                  `protobuf:"varint,6,opt,name=home_score,json=homeScore,proto3" json:"home_score,omitempty"`
	AwayScore     int32                  `protobuf:"varint,7,opt,name=away_score,json=awayScore,proto3" json:"away_score,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_proto_game_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{1}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetHomeTeamId() string {
	if x != nil {
		return x.HomeTeamId
	}
	return ""
}

func (x *Game) GetAwayTeamId() string {
	if x != nil {
		return x.AwayTeamId
	}
	return ""
}

func (x *Game) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *Game) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_STATUS_UNSPECIFIED
}

func (x *Game) GetHomeScore() int32 {
	if x != nil {
		return x.HomeScore
	}
	return 0
}

func (x *Game) GetAwayScore() int32 {
	if x != nil {
		return x.AwayScore
	}
	return 0
}

func (x *Game) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Game) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Game) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// GetAllTeams
type GetAllTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTeamsRequest) Reset() {
	*x = GetAllTeamsRequest{}
	mi := &file_proto_game_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTeamsRequest) ProtoMessage() {}

func (x *GetAllTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTeamsRequest.ProtoReflect.Descriptor instead.
func (*GetAllTeamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{2}
}

type GetAllTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTeamsResponse) Reset() {
	*x = GetAllTeamsResponse{}
	mi := &file_proto_game_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTeamsResponse) ProtoMessage() {}

func (x *GetAllTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTeamsResponse.ProtoReflect.Descriptor instead.
func (*GetAllTeamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllTeamsResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *GetAllTeamsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetTeamByID
type GetTeamByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamByIDRequest) Reset() {
	*x = GetTeamByIDRequest{}
	mi := &file_proto_game_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamByIDRequest) ProtoMessage() {}

func (x *GetTeamByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTeamByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTeamByIDRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetTeamByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamByIDResponse) Reset() {
	*x = GetTeamByIDResponse{}
	mi := &file_proto_game_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamByIDResponse) ProtoMessage() {}

func (x *GetTeamByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTeamByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTeamByIDResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

// GetTeamsByConference
type GetTeamsByConferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conference    Conference             `protobuf:"varint,1,opt,name=conference,proto3,enum=proto.Conference" json:"conference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamsByConferenceRequest) Reset() {
	*x = GetTeamsByConferenceRequest{}
	mi := &file_proto_game_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamsByConferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsByConferenceRequest) ProtoMessage() {}

func (x *GetTeamsByConferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsByConferenceRequest.ProtoReflect.Descriptor instead.
func (*GetTeamsByConferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTeamsByConferenceRequest) GetConference() Conference {
	if x != nil {
		return x.Conference
	}
	return Conference_CONFERENCE_UNSPECIFIED
}

type GetTeamsByConferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Conference    Conference             `protobuf:"varint,3,opt,name=conference,proto3,enum=proto.Conference" json:"conference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamsByConferenceResponse) Reset() {
	*x = GetTeamsByConferenceResponse{}
	mi := &file_proto_game_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamsByConferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsByConferenceResponse) ProtoMessage() {}

func (x *GetTeamsByConferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsByConferenceResponse.ProtoReflect.Descriptor instead.
func (*GetTeamsByConferenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetTeamsByConferenceResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *GetTeamsByConferenceResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTeamsByConferenceResponse) GetConference() Conference {
	if x != nil {
		return x.Conference
	}
	return Conference_CONFERENCE_UNSPECIFIED
}

// GetTeamsByDivision
type GetTeamsByDivisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Division      Division               `protobuf:"varint,1,opt,name=division,proto3,enum=proto.Division" json:"division,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamsByDivisionRequest) Reset() {
	*x = GetTeamsByDivisionRequest{}
	mi := &file_proto_game_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamsByDivisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsByDivisionRequest) ProtoMessage() {}

func (x *GetTeamsByDivisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsByDivisionRequest.ProtoReflect.Descriptor instead.
func (*GetTeamsByDivisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetTeamsByDivisionRequest) GetDivision() Division {
	if x != nil {
		return x.Division
	}
	return Division_DIVISION_UNSPECIFIED
}

type GetTeamsByDivisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Division      Division               `protobuf:"varint,3,opt,name=division,proto3,enum=proto.Division" json:"division,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamsByDivisionResponse) Reset() {
	*x = GetTeamsByDivisionResponse{}
	mi := &file_proto_game_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamsByDivisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsByDivisionResponse) ProtoMessage() {}

func (x *GetTeamsByDivisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsByDivisionResponse.ProtoReflect.Descriptor instead.
func (*GetTeamsByDivisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetTeamsByDivisionResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *GetTeamsByDivisionResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTeamsByDivisionResponse) GetDivision() Division {
	if x != nil {
		return x.Division
	}
	return Division_DIVISION_UNSPECIFIED
}

// GetAllGames
type GetAllGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllGamesRequest) Reset() {
	*x = GetAllGamesRequest{}
	mi := &file_proto_game_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGamesRequest) ProtoMessage() {}

func (x *GetAllGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGamesRequest.ProtoReflect.Descriptor instead.
func (*GetAllGamesRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{10}
}

type GetAllGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllGamesResponse) Reset() {
	*x = GetAllGamesResponse{}
	mi := &file_proto_game_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGamesResponse) ProtoMessage() {}

func (x *GetAllGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGamesResponse.ProtoReflect.Descriptor instead.
func (*GetAllGamesResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllGamesResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *GetAllGamesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetGameByID
type GetGameByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameByIDRequest) Reset() {
	*x = GetGameByIDRequest{}
	mi := &file_proto_game_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByIDRequest) ProtoMessage() {}

func (x *GetGameByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByIDRequest.ProtoReflect.Descriptor instead.
func (*GetGameByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetGameByIDRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GetGameByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameByIDResponse) Reset() {
	*x = GetGameByIDResponse{}
	mi := &file_proto_game_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByIDResponse) ProtoMessage() {}

func (x *GetGameByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByIDResponse.ProtoReflect.Descriptor instead.
func (*GetGameByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetGameByIDResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

// GetGamesByWeek
type GetGamesByWeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Week          int32                  `protobuf:"varint,1,opt,name=week,proto3" json:"week,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesByWeekRequest) Reset() {
	*x = GetGamesByWeekRequest{}
	mi := &file_proto_game_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesByWeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesByWeekRequest) ProtoMessage() {}

func (x *GetGamesByWeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesByWeekRequest.ProtoReflect.Descriptor instead.
func (*GetGamesByWeekRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetGamesByWeekRequest) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

type GetGamesByWeekResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Week          int32                  `protobuf:"varint,3,opt,name=week,proto3" json:"week,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesByWeekResponse) Reset() {
	*x = GetGamesByWeekResponse{}
	mi := &file_proto_game_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesByWeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesByWeekResponse) ProtoMessage() {}

func (x *GetGamesByWeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesByWeekResponse.ProtoReflect.Descriptor instead.
func (*GetGamesByWeekResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetGamesByWeekResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *GetGamesByWeekResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetGamesByWeekResponse) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

// GetGamesByTeam
type GetGamesByTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesByTeamRequest) Reset() {
	*x = GetGamesByTeamRequest{}
	mi := &file_proto_game_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesByTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesByTeamRequest) ProtoMessage() {}

func (x *GetGamesByTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesByTeamRequest.ProtoReflect.Descriptor instead.
func (*GetGamesByTeamRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetGamesByTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetGamesByTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	TeamId        string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesByTeamResponse) Reset() {
	*x = GetGamesByTeamResponse{}
	mi := &file_proto_game_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesByTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesByTeamResponse) ProtoMessage() {}

func (x *GetGamesByTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesByTeamResponse.ProtoReflect.Descriptor instead.
func (*GetGamesByTeamResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetGamesByTeamResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *GetGamesByTeamResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetGamesByTeamResponse) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// GetGamesByStatus
type GetGamesByStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GameStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=proto.GameStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesByStatusRequest) Reset() {
	*x = GetGamesByStatusRequest{}
	mi := &file_proto_game_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesByStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesByStatusRequest) ProtoMessage() {}

func (x *GetGamesByStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesByStatusRequest.ProtoReflect.Descriptor instead.
func (*GetGamesByStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetGamesByStatusRequest) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_STATUS_UNSPECIFIED
}

type GetGamesByStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Status        GameStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=proto.GameStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesByStatusResponse) Reset() {
	*x = GetGamesByStatusResponse{}
	mi := &file_proto_game_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesByStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesByStatusResponse) ProtoMessage() {}

func (x *GetGamesByStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesByStatusResponse.ProtoReflect.Descriptor instead.
func (*GetGamesByStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetGamesByStatusResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *GetGamesByStatusResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetGamesByStatusResponse) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_STATUS_UNSPECIFIED
}

// CreateGame (for admin/testing)
type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeTeamId    string                 `protobuf:"bytes,1,opt,name=home_team_id,json=homeTeamId,proto3" json:"home_team_id,omitempty"`
	AwayTeamId    string                 `protobuf:"bytes,2,opt,name=away_team_id,json=awayTeamId,proto3" json:"away_team_id,omitempty"`
	Week          int32                  `protobuf:"varint,3,opt,name=week,proto3" json:"week,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_proto_game_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{20}
}

func (x *CreateGameRequest) GetHomeTeamId() string {
	if x != nil {
		return x.HomeTeamId
	}
	return ""
}

func (x *CreateGameRequest) GetAwayTeamId() string {
	if x != nil {
		return x.AwayTeamId
	}
	return ""
}

func (x *CreateGameRequest) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *CreateGameRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_proto_game_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{21}
}

func (x *CreateGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *CreateGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateGameScore
type UpdateGameScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	HomeScore     int32                  `protobuf:"varint,2,opt,name=home_score,json=homeScore,proto3" json:"home_score,omitempty"`
	AwayScore     int32                  `protobuf:"varint,3,opt,name=away_score,json=awayScore,proto3" json:"away_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameScoreRequest) Reset() {
	*x = UpdateGameScoreRequest{}
	mi := &file_proto_game_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameScoreRequest) ProtoMessage() {}

func (x *UpdateGameScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameScoreRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateGameScoreRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UpdateGameScoreRequest) GetHomeScore() int32 {
	if x != nil {
		return x.HomeScore
	}
	return 0
}

func (x *UpdateGameScoreRequest) GetAwayScore() int32 {
	if x != nil {
		return x.AwayScore
	}
	return 0
}

type UpdateGameScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameScoreResponse) Reset() {
	*x = UpdateGameScoreResponse{}
	mi := &file_proto_game_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameScoreResponse) ProtoMessage() {}

func (x *UpdateGameScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameScoreResponse.ProtoReflect.Descriptor instead.
func (*UpdateGameScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateGameScoreResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *UpdateGameScoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateGameStatus
type UpdateGameStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Status        GameStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=proto.GameStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameStatusRequest) Reset() {
	*x = UpdateGameStatusRequest{}
	mi := &file_proto_game_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameStatusRequest) ProtoMessage() {}

func (x *UpdateGameStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateGameStatusRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UpdateGameStatusRequest) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_STATUS_UNSPECIFIED
}

type UpdateGameStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameStatusResponse) Reset() {
	*x = UpdateGameStatusResponse{}
	mi := &file_proto_game_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameStatusResponse) ProtoMessage() {}

func (x *UpdateGameStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateGameStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateGameStatusResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *UpdateGameStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_game_service_proto protoreflect.FileDescriptor

const file_proto_game_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/game_service.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x01\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\"\n" +
	"\fabbreviation\x18\x04 \x01(\tR\fabbreviation\x121\n" +
	"\n" +
	"conference\x18\x05 \x01(\x0e2\x11.proto.ConferenceR\n" +
	"conference\x12+\n" +
	"\bdivision\x18\x06 \x01(\x0e2\x0f.proto.DivisionR\bdivision\x12\x19\n" +
	"\blogo_url\x18\a \x01(\tR\alogoUrl\x12\x18\n" +
	"\astadium\x18\b \x01(\tR\astadium\"\x90\x03\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\fhome_team_id\x18\x02 \x01(\tR\n" +
	"homeTeamId\x12 \n" +
	"\faway_team_id\x18\x03 \x01(\tR\n" +
	"awayTeamId\x12\x12\n" +
	"\x04week\x18\x04 \x01(\x05R\x04week\x12)\n" +
	"\x06status\x18\x05 \x01(\x0e2\x11.proto.GameStatusR\x06status\x12\x1d\n" +
	"\n" +
	"home_score\x18\x06 \x01(\x05R\thomeScore\x12\x1d\n" +
	"\n" +
	"away_score\x18\a \x01(\x05R\tawayScore\x12=\n" +
	"\fscheduled_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x14\n" +
	"\x12GetAllTeamsRequest\"N\n" +
	"\x13GetAllTeamsResponse\x12!\n" +
	"\x05teams\x18\x01 \x03(\v2\v.proto.TeamR\x05teams\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"-\n" +
	"\x12GetTeamByIDRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"6\n" +
	"\x13GetTeamByIDResponse\x12\x1f\n" +
	"\x04team\x18\x01 \x01(\v2\v.proto.TeamR\x04team\"P\n" +
	"\x1bGetTeamsByConferenceRequest\x121\n" +
	"\n" +
	"conference\x18\x01 \x01(\x0e2\x11.proto.ConferenceR\n" +
	"conference\"\x8a\x01\n" +
	"\x1cGetTeamsByConferenceResponse\x12!\n" +
	"\x05teams\x18\x01 \x03(\v2\v.proto.TeamR\x05teams\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x121\n" +
	"\n" +
	"conference\x18\x03 \x01(\x0e2\x11.proto.ConferenceR\n" +
	"conference\"H\n" +
	"\x19GetTeamsByDivisionRequest\x12+\n" +
	"\bdivision\x18\x01 \x01(\x0e2\x0f.proto.DivisionR\bdivision\"\x82\x01\n" +
	"\x1aGetTeamsByDivisionResponse\x12!\n" +
	"\x05teams\x18\x01 \x03(\v2\v.proto.TeamR\x05teams\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12+\n" +
	"\bdivision\x18\x03 \x01(\x0e2\x0f.proto.DivisionR\bdivision\"\x14\n" +
	"\x12GetAllGamesRequest\"N\n" +
	"\x13GetAllGamesResponse\x12!\n" +
	"\x05games\x18\x01 \x03(\v2\v.proto.GameR\x05games\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"-\n" +
	"\x12GetGameByIDRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"6\n" +
	"\x13GetGameByIDResponse\x12\x1f\n" +
	"\x04game\x18\x01 \x01(\v2\v.proto.GameR\x04game\"+\n" +
	"\x15GetGamesByWeekRequest\x12\x12\n" +
	"\x04week\x18\x01 \x01(\x05R\x04week\"e\n" +
	"\x16GetGamesByWeekResponse\x12!\n" +
	"\x05games\x18\x01 \x03(\v2\v.proto.GameR\x05games\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04week\x18\x03 \x01(\x05R\x04week\"0\n" +
	"\x15GetGamesByTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"j\n" +
	"\x16GetGamesByTeamResponse\x12!\n" +
	"\x05games\x18\x01 \x03(\v2\v.proto.GameR\x05games\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\"D\n" +
	"\x17GetGamesByStatusRequest\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.proto.GameStatusR\x06status\"~\n" +
	"\x18GetGamesByStatusResponse\x12!\n" +
	"\x05games\x18\x01 \x03(\v2\v.proto.GameR\x05games\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.proto.GameStatusR\x06status\"\xaa\x01\n" +
	"\x11CreateGameRequest\x12 \n" +
	"\fhome_team_id\x18\x01 \x01(\tR\n" +
	"homeTeamId\x12 \n" +
	"\faway_team_id\x18\x02 \x01(\tR\n" +
	"awayTeamId\x12\x12\n" +
	"\x04week\x18\x03 \x01(\x05R\x04week\x12=\n" +
	"\fscheduled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\"O\n" +
	"\x12CreateGameResponse\x12\x1f\n" +
	"\x04game\x18\x01 \x01(\v2\v.proto.GameR\x04game\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"o\n" +
	"\x16UpdateGameScoreRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"home_score\x18\x02 \x01(\x05R\thomeScore\x12\x1d\n" +
	"\n" +
	"away_score\x18\x03 \x01(\x05R\tawayScore\"T\n" +
	"\x17UpdateGameScoreResponse\x12\x1f\n" +
	"\x04game\x18\x01 \x01(\v2\v.proto.GameR\x04game\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x17UpdateGameStatusRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.proto.GameStatusR\x06status\"U\n" +
	"\x18UpdateGameStatusResponse\x12\x1f\n" +
	"\x04game\x18\x01 \x01(\v2\v.proto.GameR\x04game\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*P\n" +
	"\n" +
	"Conference\x12\x1a\n" +
	"\x16CONFERENCE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCONFERENCE_AFC\x10\x01\x12\x12\n" +
	"\x0eCONFERENCE_NFC\x10\x02*\xe0\x01\n" +
	"\bDivision\x12\x18\n" +
	"\x14DIVISION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DIVISION_AFC_EAST\x10\x01\x12\x16\n" +
	"\x12DIVISION_AFC_NORTH\x10\x02\x12\x16\n" +
	"\x12DIVISION_AFC_SOUTH\x10\x03\x12\x15\n" +
	"\x11DIVISION_AFC_WEST\x10\x04\x12\x15\n" +
	"\x11DIVISION_NFC_EAST\x10\x05\x12\x16\n" +
	"\x12DIVISION_NFC_NORTH\x10\x06\x12\x16\n" +
	"\x12DIVISION_NFC_SOUTH\x10\a\x12\x15\n" +
	"\x11DIVISION_NFC_WEST\x10\b*\xb1\x01\n" +
	"\n" +
	"GameStatus\x12\x1b\n" +
	"\x17GAME_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15GAME_STATUS_SCHEDULED\x10\x01\x12\x1b\n" +
	"\x17GAME_STATUS_IN_PROGRESS\x10\x02\x12\x19\n" +
	"\x15GAME_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15GAME_STATUS_POSTPONED\x10\x04\x12\x18\n" +
	"\x14GAME_STATUS_CANCELED\x10\x052\xbe\a\n" +
	"\vGameService\x12D\n" +
	"\vGetAllTeams\x12\x19.proto.GetAllTeamsRequest\x1a\x1a.proto.GetAllTeamsResponse\x12D\n" +
	"\vGetTeamByID\x12\x19.proto.GetTeamByIDRequest\x1a\x1a.proto.GetTeamByIDResponse\x12_\n" +
	"\x14GetTeamsByConference\x12\".proto.GetTeamsByConferenceRequest\x1a#.proto.GetTeamsByConferenceResponse\x12Y\n" +
	"\x12GetTeamsByDivision\x12 .proto.GetTeamsByDivisionRequest\x1a!.proto.GetTeamsByDivisionResponse\x12D\n" +
	"\vGetAllGames\x12\x19.proto.GetAllGamesRequest\x1a\x1a.proto.GetAllGamesResponse\x12D\n" +
	"\vGetGameByID\x12\x19.proto.GetGameByIDRequest\x1a\x1a.proto.GetGameByIDResponse\x12M\n" +
	"\x0eGetGamesByWeek\x12\x1c.proto.GetGamesByWeekRequest\x1a\x1d.proto.GetGamesByWeekResponse\x12M\n" +
	"\x0eGetGamesByTeam\x12\x1c.proto.GetGamesByTeamRequest\x1a\x1d.proto.GetGamesByTeamResponse\x12S\n" +
	"\x10GetGamesByStatus\x12\x1e.proto.GetGamesByStatusRequest\x1a\x1f.proto.GetGamesByStatusResponse\x12A\n" +
	"\n" +
	"CreateGame\x12\x18.proto.CreateGameRequest\x1a\x19.proto.CreateGameResponse\x12P\n" +
	"\x0fUpdateGameScore\x12\x1d.proto.UpdateGameScoreRequest\x1a\x1e.proto.UpdateGameScoreResponse\x12S\n" +
	"\x10UpdateGameStatus\x12\x1e.proto.UpdateGameStatusRequest\x1a\x1f.proto.UpdateGameStatusResponseB\x19Z\x17kickoff.com/proto;protob\x06proto3"

var (
	file_proto_game_service_proto_rawDescOnce sync.Once
	file_proto_game_service_proto_rawDescData []byte
)

func file_proto_game_service_proto_rawDescGZIP() []byte {
	file_proto_game_service_proto_rawDescOnce.Do(func() {
		file_proto_game_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_service_proto_rawDesc), len(file_proto_game_service_proto_rawDesc)))
	})
	return file_proto_game_service_proto_rawDescData
}

var file_proto_game_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_game_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_game_service_proto_goTypes = []any{
	(Conference)(0),                      // 0: proto.Conference
	(Division)(0),                        // 1: proto.Division
	(GameStatus)(0),                      // 2: proto.GameStatus
	(*Team)(nil),                         // 3: proto.Team
	(*Game)(nil),                         // 4: proto.Game
	(*GetAllTeamsRequest)(nil),           // 5: proto.GetAllTeamsRequest
	(*GetAllTeamsResponse)(nil),          // 6: proto.GetAllTeamsResponse
	(*GetTeamByIDRequest)(nil),           // 7: proto.GetTeamByIDRequest
	(*GetTeamByIDResponse)(nil),          // 8: proto.GetTeamByIDResponse
	(*GetTeamsByConferenceRequest)(nil),  // 9: proto.GetTeamsByConferenceRequest
	(*GetTeamsByConferenceResponse)(nil), // 10: proto.GetTeamsByConferenceResponse
	(*GetTeamsByDivisionRequest)(nil),    // 11: proto.GetTeamsByDivisionRequest
	(*GetTeamsByDivisionResponse)(nil),   // 12: proto.GetTeamsByDivisionResponse
	(*GetAllGamesRequest)(nil),           // 13: proto.GetAllGamesRequest
	(*GetAllGamesResponse)(nil),          // 14: proto.GetAllGamesResponse
	(*GetGameByIDRequest)(nil),           // 15: proto.GetGameByIDRequest
	(*GetGameByIDResponse)(nil),          // 16: proto.GetGameByIDResponse
	(*GetGamesByWeekRequest)(nil),        // 17: proto.GetGamesByWeekRequest
	(*GetGamesByWeekResponse)(nil),       // 18: proto.GetGamesByWeekResponse
	(*GetGamesByTeamRequest)(nil),        // 19: proto.GetGamesByTeamRequest
	(*GetGamesByTeamResponse)(nil),       // 20: proto.GetGamesByTeamResponse
	(*GetGamesByStatusRequest)(nil),      // 21: proto.GetGamesByStatusRequest
	(*GetGamesByStatusResponse)(nil),     // 22: proto.GetGamesByStatusResponse
	(*CreateGameRequest)(nil),            // 23: proto.CreateGameRequest
	(*CreateGameResponse)(nil),           // 24: proto.CreateGameResponse
	(*UpdateGameScoreRequest)(nil),       // 25: proto.UpdateGameScoreRequest
	(*UpdateGameScoreResponse)(nil),      // 26: proto.UpdateGameScoreResponse
	(*UpdateGameStatusRequest)(nil),      // 27: proto.UpdateGameStatusRequest
	(*UpdateGameStatusResponse)(nil),     // 28: proto.UpdateGameStatusResponse
	(*timestamppb.Timestamp)(nil),        // 29: google.protobuf.Timestamp
}
var file_proto_game_service_proto_depIdxs = []int32{
	0,  // 0: proto.Team.conference:type_name -> proto.Conference
	1,  // 1: proto.Team.division:type_name -> proto.Division
	2,  // 2: proto.Game.status:type_name -> proto.GameStatus
	29, // 3: proto.Game.scheduled_at:type_name -> google.protobuf.Timestamp
	29, // 4: proto.Game.started_at:type_name -> google.protobuf.Timestamp
	29, // 5: proto.Game.completed_at:type_name -> google.protobuf.Timestamp
	3,  // 6: proto.GetAllTeamsResponse.teams:type_name -> proto.Team
	3,  // 7: proto.GetTeamByIDResponse.team:type_name -> proto.Team
	0,  // 8: proto.GetTeamsByConferenceRequest.conference:type_name -> proto.Conference
	3,  // 9: proto.GetTeamsByConferenceResponse.teams:type_name -> proto.Team
	0,  // 10: proto.GetTeamsByConferenceResponse.conference:type_name -> proto.Conference
	1,  // 11: proto.GetTeamsByDivisionRequest.division:type_name -> proto.Division
	3,  // 12: proto.GetTeamsByDivisionResponse.teams:type_name -> proto.Team
	1,  // 13: proto.GetTeamsByDivisionResponse.division:type_name -> proto.Division
	4,  // 14: proto.GetAllGamesResponse.games:type_name -> proto.Game
	4,  // 15: proto.GetGameByIDResponse.game:type_name -> proto.Game
	4,  // 16: proto.GetGamesByWeekResponse.games:type_name -> proto.Game
	4,  // 17: proto.GetGamesByTeamResponse.games:type_name -> proto.Game
	2,  // 18: proto.GetGamesByStatusRequest.status:type_name -> proto.GameStatus
	4,  // 19: proto.GetGamesByStatusResponse.games:type_name -> proto.Game
	2,  // 20: proto.GetGamesByStatusResponse.status:type_name -> proto.GameStatus
	29, // 21: proto.CreateGameRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	4,  // 22: proto.CreateGameResponse.game:type_name -> proto.Game
	4,  // 23: proto.UpdateGameScoreResponse.game:type_name -> proto.Game
	2,  // 24: proto.UpdateGameStatusRequest.status:type_name -> proto.GameStatus
	4,  // 25: proto.UpdateGameStatusResponse.game:type_name -> proto.Game
	5,  // 26: proto.GameService.GetAllTeams:input_type -> proto.GetAllTeamsRequest
	7,  // 27: proto.GameService.GetTeamByID:input_type -> proto.GetTeamByIDRequest
	9,  // 28: proto.GameService.GetTeamsByConference:input_type -> proto.GetTeamsByConferenceRequest
	11, // 29: proto.GameService.GetTeamsByDivision:input_type -> proto.GetTeamsByDivisionRequest
	13, // 30: proto.GameService.GetAllGames:input_type -> proto.GetAllGamesRequest
	15, // 31: proto.GameService.GetGameByID:input_type -> proto.GetGameByIDRequest
	17, // 32: proto.GameService.GetGamesByWeek:input_type -> proto.GetGamesByWeekRequest
	19, // 33: proto.GameService.GetGamesByTeam:input_type -> proto.GetGamesByTeamRequest
	21, // 34: proto.GameService.GetGamesByStatus:input_type -> proto.GetGamesByStatusRequest
	23, // 35: proto.GameService.CreateGame:input_type -> proto.CreateGameRequest
	25, // 36: proto.GameService.UpdateGameScore:input_type -> proto.UpdateGameScoreRequest
	27, // 37: proto.GameService.UpdateGameStatus:input_type -> proto.UpdateGameStatusRequest
	6,  // 38: proto.GameService.GetAllTeams:output_type -> proto.GetAllTeamsResponse
	8,  // 39: proto.GameService.GetTeamByID:output_type -> proto.GetTeamByIDResponse
	10, // 40: proto.GameService.GetTeamsByConference:output_type -> proto.GetTeamsByConferenceResponse
	12, // 41: proto.GameService.GetTeamsByDivision:output_type -> proto.GetTeamsByDivisionResponse
	14, // 42: proto.GameService.GetAllGames:output_type -> proto.GetAllGamesResponse
	16, // 43: proto.GameService.GetGameByID:output_type -> proto.GetGameByIDResponse
	18, // 44: proto.GameService.GetGamesByWeek:output_type -> proto.GetGamesByWeekResponse
	20, // 45: proto.GameService.GetGamesByTeam:output_type -> proto.GetGamesByTeamResponse
	22, // 46: proto.GameService.GetGamesByStatus:output_type -> proto.GetGamesByStatusResponse
	24, // 47: proto.GameService.CreateGame:output_type -> proto.CreateGameResponse
	26, // 48: proto.GameService.UpdateGameScore:output_type -> proto.UpdateGameScoreResponse
	28, // 49: proto.GameService.UpdateGameStatus:output_type -> proto.UpdateGameStatusResponse
	38, // [38:50] is the sub-list for method output_type
	26, // [26:38] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_game_service_proto_init() }
func file_proto_game_service_proto_init() {
	if File_proto_game_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_service_proto_rawDesc), len(file_proto_game_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_service_proto_goTypes,
		DependencyIndexes: file_proto_game_service_proto_depIdxs,
		EnumInfos:         file_proto_game_service_proto_enumTypes,
		MessageInfos:      file_proto_game_service_proto_msgTypes,
	}.Build()
	File_proto_game_service_proto = out.File
	file_proto_game_service_proto_goTypes = nil
	file_proto_game_service_proto_depIdxs = nil
}
