// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/game_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_GetAllTeams_FullMethodName          = "/proto.GameService/GetAllTeams"
	GameService_GetTeamByID_FullMethodName          = "/proto.GameService/GetTeamByID"
	GameService_GetTeamsByConference_FullMethodName = "/proto.GameService/GetTeamsByConference"
	GameService_GetTeamsByDivision_FullMethodName   = "/proto.GameService/GetTeamsByDivision"
	GameService_GetAllGames_FullMethodName          = "/proto.GameService/GetAllGames"
	GameService_GetGameByID_FullMethodName          = "/proto.GameService/GetGameByID"
	GameService_GetGamesByWeek_FullMethodName       = "/proto.GameService/GetGamesByWeek"
	GameService_GetGamesByTeam_FullMethodName       = "/proto.GameService/GetGamesByTeam"
	GameService_GetGamesByStatus_FullMethodName     = "/proto.GameService/GetGamesByStatus"
	GameService_CreateGame_FullMethodName           = "/proto.GameService/CreateGame"
	GameService_UpdateGameScore_FullMethodName      = "/proto.GameService/UpdateGameScore"
	GameService_UpdateGameStatus_FullMethodName     = "/proto.GameService/UpdateGameStatus"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	// Team operations
	GetAllTeams(ctx context.Context, in *GetAllTeamsRequest, opts ...grpc.CallOption) (*GetAllTeamsResponse, error)
	GetTeamByID(ctx context.Context, in *GetTeamByIDRequest, opts ...grpc.CallOption) (*GetTeamByIDResponse, error)
	GetTeamsByConference(ctx context.Context, in *GetTeamsByConferenceRequest, opts ...grpc.CallOption) (*GetTeamsByConferenceResponse, error)
	GetTeamsByDivision(ctx context.Context, in *GetTeamsByDivisionRequest, opts ...grpc.CallOption) (*GetTeamsByDivisionResponse, error)
	// Game operations
	GetAllGames(ctx context.Context, in *GetAllGamesRequest, opts ...grpc.CallOption) (*GetAllGamesResponse, error)
	GetGameByID(ctx context.Context, in *GetGameByIDRequest, opts ...grpc.CallOption) (*GetGameByIDResponse, error)
	GetGamesByWeek(ctx context.Context, in *GetGamesByWeekRequest, opts ...grpc.CallOption) (*GetGamesByWeekResponse, error)
	GetGamesByTeam(ctx context.Context, in *GetGamesByTeamRequest, opts ...grpc.CallOption) (*GetGamesByTeamResponse, error)
	GetGamesByStatus(ctx context.Context, in *GetGamesByStatusRequest, opts ...grpc.CallOption) (*GetGamesByStatusResponse, error)
	// Game management (admin/internal)
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	UpdateGameScore(ctx context.Context, in *UpdateGameScoreRequest, opts ...grpc.CallOption) (*UpdateGameScoreResponse, error)
	UpdateGameStatus(ctx context.Context, in *UpdateGameStatusRequest, opts ...grpc.CallOption) (*UpdateGameStatusResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) GetAllTeams(ctx context.Context, in *GetAllTeamsRequest, opts ...grpc.CallOption) (*GetAllTeamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllTeamsResponse)
	err := c.cc.Invoke(ctx, GameService_GetAllTeams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetTeamByID(ctx context.Context, in *GetTeamByIDRequest, opts ...grpc.CallOption) (*GetTeamByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamByIDResponse)
	err := c.cc.Invoke(ctx, GameService_GetTeamByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetTeamsByConference(ctx context.Context, in *GetTeamsByConferenceRequest, opts ...grpc.CallOption) (*GetTeamsByConferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamsByConferenceResponse)
	err := c.cc.Invoke(ctx, GameService_GetTeamsByConference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetTeamsByDivision(ctx context.Context, in *GetTeamsByDivisionRequest, opts ...grpc.CallOption) (*GetTeamsByDivisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamsByDivisionResponse)
	err := c.cc.Invoke(ctx, GameService_GetTeamsByDivision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetAllGames(ctx context.Context, in *GetAllGamesRequest, opts ...grpc.CallOption) (*GetAllGamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllGamesResponse)
	err := c.cc.Invoke(ctx, GameService_GetAllGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGameByID(ctx context.Context, in *GetGameByIDRequest, opts ...grpc.CallOption) (*GetGameByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameByIDResponse)
	err := c.cc.Invoke(ctx, GameService_GetGameByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGamesByWeek(ctx context.Context, in *GetGamesByWeekRequest, opts ...grpc.CallOption) (*GetGamesByWeekResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGamesByWeekResponse)
	err := c.cc.Invoke(ctx, GameService_GetGamesByWeek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGamesByTeam(ctx context.Context, in *GetGamesByTeamRequest, opts ...grpc.CallOption) (*GetGamesByTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGamesByTeamResponse)
	err := c.cc.Invoke(ctx, GameService_GetGamesByTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGamesByStatus(ctx context.Context, in *GetGamesByStatusRequest, opts ...grpc.CallOption) (*GetGamesByStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGamesByStatusResponse)
	err := c.cc.Invoke(ctx, GameService_GetGamesByStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, GameService_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdateGameScore(ctx context.Context, in *UpdateGameScoreRequest, opts ...grpc.CallOption) (*UpdateGameScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameScoreResponse)
	err := c.cc.Invoke(ctx, GameService_UpdateGameScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdateGameStatus(ctx context.Context, in *UpdateGameStatusRequest, opts ...grpc.CallOption) (*UpdateGameStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameStatusResponse)
	err := c.cc.Invoke(ctx, GameService_UpdateGameStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility.
type GameServiceServer interface {
	// Team operations
	GetAllTeams(context.Context, *GetAllTeamsRequest) (*GetAllTeamsResponse, error)
	GetTeamByID(context.Context, *GetTeamByIDRequest) (*GetTeamByIDResponse, error)
	GetTeamsByConference(context.Context, *GetTeamsByConferenceRequest) (*GetTeamsByConferenceResponse, error)
	GetTeamsByDivision(context.Context, *GetTeamsByDivisionRequest) (*GetTeamsByDivisionResponse, error)
	// Game operations
	GetAllGames(context.Context, *GetAllGamesRequest) (*GetAllGamesResponse, error)
	GetGameByID(context.Context, *GetGameByIDRequest) (*GetGameByIDResponse, error)
	GetGamesByWeek(context.Context, *GetGamesByWeekRequest) (*GetGamesByWeekResponse, error)
	GetGamesByTeam(context.Context, *GetGamesByTeamRequest) (*GetGamesByTeamResponse, error)
	GetGamesByStatus(context.Context, *GetGamesByStatusRequest) (*GetGamesByStatusResponse, error)
	// Game management (admin/internal)
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	UpdateGameScore(context.Context, *UpdateGameScoreRequest) (*UpdateGameScoreResponse, error)
	UpdateGameStatus(context.Context, *UpdateGameStatusRequest) (*UpdateGameStatusResponse, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) GetAllTeams(context.Context, *GetAllTeamsRequest) (*GetAllTeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTeams not implemented")
}
func (UnimplementedGameServiceServer) GetTeamByID(context.Context, *GetTeamByIDRequest) (*GetTeamByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamByID not implemented")
}
func (UnimplementedGameServiceServer) GetTeamsByConference(context.Context, *GetTeamsByConferenceRequest) (*GetTeamsByConferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsByConference not implemented")
}
func (UnimplementedGameServiceServer) GetTeamsByDivision(context.Context, *GetTeamsByDivisionRequest) (*GetTeamsByDivisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsByDivision not implemented")
}
func (UnimplementedGameServiceServer) GetAllGames(context.Context, *GetAllGamesRequest) (*GetAllGamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllGames not implemented")
}
func (UnimplementedGameServiceServer) GetGameByID(context.Context, *GetGameByIDRequest) (*GetGameByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameByID not implemented")
}
func (UnimplementedGameServiceServer) GetGamesByWeek(context.Context, *GetGamesByWeekRequest) (*GetGamesByWeekResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGamesByWeek not implemented")
}
func (UnimplementedGameServiceServer) GetGamesByTeam(context.Context, *GetGamesByTeamRequest) (*GetGamesByTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGamesByTeam not implemented")
}
func (UnimplementedGameServiceServer) GetGamesByStatus(context.Context, *GetGamesByStatusRequest) (*GetGamesByStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGamesByStatus not implemented")
}
func (UnimplementedGameServiceServer) CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedGameServiceServer) UpdateGameScore(context.Context, *UpdateGameScoreRequest) (*UpdateGameScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGameScore not implemented")
}
func (UnimplementedGameServiceServer) UpdateGameStatus(context.Context, *UpdateGameStatusRequest) (*UpdateGameStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGameStatus not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}
func (UnimplementedGameServiceServer) testEmbeddedByValue()                     {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call pancis, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_GetAllTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetAllTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetAllTeams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetAllTeams(ctx, req.(*GetAllTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetTeamByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetTeamByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetTeamByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetTeamByID(ctx, req.(*GetTeamByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetTeamsByConference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamsByConferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetTeamsByConference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetTeamsByConference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetTeamsByConference(ctx, req.(*GetTeamsByConferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetTeamsByDivision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamsByDivisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetTeamsByDivision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetTeamsByDivision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetTeamsByDivision(ctx, req.(*GetTeamsByDivisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetAllGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetAllGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetAllGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetAllGames(ctx, req.(*GetAllGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGameByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGameByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameByID(ctx, req.(*GetGameByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGamesByWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGamesByWeekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGamesByWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGamesByWeek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGamesByWeek(ctx, req.(*GetGamesByWeekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGamesByTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGamesByTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGamesByTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGamesByTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGamesByTeam(ctx, req.(*GetGamesByTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGamesByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGamesByStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGamesByStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGamesByStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGamesByStatus(ctx, req.(*GetGamesByStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdateGameScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdateGameScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_UpdateGameScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdateGameScore(ctx, req.(*UpdateGameScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdateGameStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdateGameStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_UpdateGameStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdateGameStatus(ctx, req.(*UpdateGameStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllTeams",
			Handler:    _GameService_GetAllTeams_Handler,
		},
		{
			MethodName: "GetTeamByID",
			Handler:    _GameService_GetTeamByID_Handler,
		},
		{
			MethodName: "GetTeamsByConference",
			Handler:    _GameService_GetTeamsByConference_Handler,
		},
		{
			MethodName: "GetTeamsByDivision",
			Handler:    _GameService_GetTeamsByDivision_Handler,
		},
		{
			MethodName: "GetAllGames",
			Handler:    _GameService_GetAllGames_Handler,
		},
		{
			MethodName: "GetGameByID",
			Handler:    _GameService_GetGameByID_Handler,
		},
		{
			MethodName: "GetGamesByWeek",
			Handler:    _GameService_GetGamesByWeek_Handler,
		},
		{
			MethodName: "GetGamesByTeam",
			Handler:    _GameService_GetGamesByTeam_Handler,
		},
		{
			MethodName: "GetGamesByStatus",
			Handler:    _GameService_GetGamesByStatus_Handler,
		},
		{
			MethodName: "CreateGame",
			Handler:    _GameService_CreateGame_Handler,
		},
		{
			MethodName: "UpdateGameScore",
			Handler:    _GameService_UpdateGameScore_Handler,
		},
		{
			MethodName: "UpdateGameStatus",
			Handler:    _GameService_UpdateGameStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/game_service.proto",
}
