// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/leaderboard_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CorrectPicks  int32                  `protobuf:"varint,2,opt,name=correct_picks,json=correctPicks,proto3" json:"correct_picks,omitempty"`
	TotalPicks    int32                  `protobuf:"varint,3,opt,name=total_picks,json=totalPicks,proto3" json:"total_picks,omitempty"`
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Rank          int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserScore) Reset() {
	*x = UserScore{}
	mi := &file_proto_leaderboard_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserScore) ProtoMessage() {}

func (x *UserScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserScore.ProtoReflect.Descriptor instead.
func (*UserScore) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserScore) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserScore) GetCorrectPicks() int32 {
	if x != nil {
		return x.CorrectPicks
	}
	return 0
}

func (x *UserScore) GetTotalPicks() int32 {
	if x != nil {
		return x.TotalPicks
	}
	return 0
}

func (x *UserScore) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *UserScore) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type PredictionDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GameId          string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PredictedWinner string                 `protobuf:"bytes,2,opt,name=predicted_winner,json=predictedWinner,proto3" json:"predicted_winner,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ActualWinner    string                 `protobuf:"bytes,4,opt,name=actual_winner,json=actualWinner,proto3" json:"actual_winner,omitempty"`
	Correct         bool                   `protobuf:"varint,5,opt,name=correct,proto3" json:"correct,omitempty"`
	GameStatus      string                 `protobuf:"bytes,6,opt,name=game_status,json=gameStatus,proto3" json:"game_status,omitempty"` // "pending", "finished"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PredictionDetail) Reset() {
	*x = PredictionDetail{}
	mi := &file_proto_leaderboard_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionDetail) ProtoMessage() {}

func (x *PredictionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionDetail.ProtoReflect.Descriptor instead.
func (*PredictionDetail) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_service_proto_rawDescGZIP(), []int{1}
}

func (x *PredictionDetail) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PredictionDetail) GetPredictedWinner() string {
	if x != nil {
		return x.PredictedWinner
	}
	return ""
}

func (x *PredictionDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PredictionDetail) GetActualWinner() string {
	if x != nil {
		return x.ActualWinner
	}
	return ""
}

func (x *PredictionDetail) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

func (x *PredictionDetail) GetGameStatus() string {
	if x != nil {
		return x.GameStatus
	}
	return ""
}

// GetLeaderboard
type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`   // Optional: limit number of results
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // Optional: pagination offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_proto_leaderboard_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLeaderboardRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaderboard   []*UserScore           `protobuf:"bytes,1,rep,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	TotalUsers    int32                  `protobuf:"varint,2,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	GamesFinished int32                  `protobuf:"varint,3,opt,name=games_finished,json=gamesFinished,proto3" json:"games_finished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_proto_leaderboard_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetLeaderboardResponse) GetLeaderboard() []*UserScore {
	if x != nil {
		return x.Leaderboard
	}
	return nil
}

func (x *GetLeaderboardResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetLeaderboardResponse) GetGamesFinished() int32 {
	if x != nil {
		return x.GamesFinished
	}
	return 0
}

// GetUserStats
type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_proto_leaderboard_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserStats        *UserScore             `protobuf:"bytes,1,opt,name=user_stats,json=userStats,proto3" json:"user_stats,omitempty"`
	Predictions      []*PredictionDetail    `protobuf:"bytes,2,rep,name=predictions,proto3" json:"predictions,omitempty"`
	TotalPredictions int32                  `protobuf:"varint,3,opt,name=total_predictions,json=totalPredictions,proto3" json:"total_predictions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserStatsResponse) Reset() {
	*x = GetUserStatsResponse{}
	mi := &file_proto_leaderboard_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsResponse) ProtoMessage() {}

func (x *GetUserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserStatsResponse) GetUserStats() *UserScore {
	if x != nil {
		return x.UserStats
	}
	return nil
}

func (x *GetUserStatsResponse) GetPredictions() []*PredictionDetail {
	if x != nil {
		return x.Predictions
	}
	return nil
}

func (x *GetUserStatsResponse) GetTotalPredictions() int32 {
	if x != nil {
		return x.TotalPredictions
	}
	return 0
}

// GetTopUsers
type GetTopUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopN          int32                  `protobuf:"varint,1,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"` // Get top N users (e.g., top 10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopUsersRequest) Reset() {
	*x = GetTopUsersRequest{}
	mi := &file_proto_leaderboard_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersRequest) ProtoMessage() {}

func (x *GetTopUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersRequest.ProtoReflect.Descriptor instead.
func (*GetTopUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopUsersRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type GetTopUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopUsers      []*UserScore           `protobuf:"bytes,1,rep,name=top_users,json=topUsers,proto3" json:"top_users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopUsersResponse) Reset() {
	*x = GetTopUsersResponse{}
	mi := &file_proto_leaderboard_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersResponse) ProtoMessage() {}

func (x *GetTopUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersResponse.ProtoReflect.Descriptor instead.
func (*GetTopUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetTopUsersResponse) GetTopUsers() []*UserScore {
	if x != nil {
		return x.TopUsers
	}
	return nil
}

func (x *GetTopUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetUserRank
type GetUserRankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRankRequest) Reset() {
	*x = GetUserRankRequest{}
	mi := &file_proto_leaderboard_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRankRequest) ProtoMessage() {}

func (x *GetUserRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRankRequest.ProtoReflect.Descriptor instead.
func (*GetUserRankRequest) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserRankRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserRankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserScore     *UserScore             `protobuf:"bytes,1,opt,name=user_score,json=userScore,proto3" json:"user_score,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	TotalUsers    int32                  `protobuf:"varint,3,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRankResponse) Reset() {
	*x = GetUserRankResponse{}
	mi := &file_proto_leaderboard_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRankResponse) ProtoMessage() {}

func (x *GetUserRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRankResponse.ProtoReflect.Descriptor instead.
func (*GetUserRankResponse) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserRankResponse) GetUserScore() *UserScore {
	if x != nil {
		return x.UserScore
	}
	return nil
}

func (x *GetUserRankResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *GetUserRankResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

// RecalculateLeaderboard (Admin operation)
type RecalculateLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecalculateLeaderboardRequest) Reset() {
	*x = RecalculateLeaderboardRequest{}
	mi := &file_proto_leaderboard_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalculateLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalculateLeaderboardRequest) ProtoMessage() {}

func (x *RecalculateLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalculateLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*RecalculateLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_service_proto_rawDescGZIP(), []int{10}
}

type RecalculateLeaderboardResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	UsersProcessed int32                  `protobuf:"varint,2,opt,name=users_processed,json=usersProcessed,proto3" json:"users_processed,omitempty"`
	GamesEvaluated int32                  `protobuf:"varint,3,opt,name=games_evaluated,json=gamesEvaluated,proto3" json:"games_evaluated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecalculateLeaderboardResponse) Reset() {
	*x = RecalculateLeaderboardResponse{}
	mi := &file_proto_leaderboard_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalculateLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalculateLeaderboardResponse) ProtoMessage() {}

func (x *RecalculateLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalculateLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*RecalculateLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_service_proto_rawDescGZIP(), []int{11}
}

func (x *RecalculateLeaderboardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecalculateLeaderboardResponse) GetUsersProcessed() int32 {
	if x != nil {
		return x.UsersProcessed
	}
	return 0
}

func (x *RecalculateLeaderboardResponse) GetGamesEvaluated() int32 {
	if x != nil {
		return x.GamesEvaluated
	}
	return 0
}

var File_proto_leaderboard_service_proto protoreflect.FileDescriptor

const file_proto_leaderboard_service_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/leaderboard_service.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x01\n" +
	"\tUserScore\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rcorrect_picks\x18\x02 \x01(\x05R\fcorrectPicks\x12\x1f\n" +
	"\vtotal_picks\x18\x03 \x01(\x05R\n" +
	"totalPicks\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\"\xf1\x01\n" +
	"\x10PredictionDetail\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12)\n" +
	"\x10predicted_winner\x18\x02 \x01(\tR\x0fpredictedWinner\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12#\n" +
	"\ractual_winner\x18\x04 \x01(\tR\factualWinner\x12\x18\n" +
	"\acorrect\x18\x05 \x01(\bR\acorrect\x12\x1f\n" +
	"\vgame_status\x18\x06 \x01(\tR\n" +
	"gameStatus\"E\n" +
	"\x15GetLeaderboardRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x94\x01\n" +
	"\x16GetLeaderboardResponse\x122\n" +
	"\vleaderboard\x18\x01 \x03(\v2\x10.proto.UserScoreR\vleaderboard\x12\x1f\n" +
	"\vtotal_users\x18\x02 \x01(\x05R\n" +
	"totalUsers\x12%\n" +
	"\x0egames_finished\x18\x03 \x01(\x05R\rgamesFinished\".\n" +
	"\x13GetUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xaf\x01\n" +
	"\x14GetUserStatsResponse\x12/\n" +
	"\n" +
	"user_stats\x18\x01 \x01(\v2\x10.proto.UserScoreR\tuserStats\x129\n" +
	"\vpredictions\x18\x02 \x03(\v2\x17.proto.PredictionDetailR\vpredictions\x12+\n" +
	"\x11total_predictions\x18\x03 \x01(\x05R\x10totalPredictions\")\n" +
	"\x12GetTopUsersRequest\x12\x13\n" +
	"\x05top_n\x18\x01 \x01(\x05R\x04topN\"Z\n" +
	"\x13GetTopUsersResponse\x12-\n" +
	"\ttop_users\x18\x01 \x03(\v2\x10.proto.UserScoreR\btopUsers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"-\n" +
	"\x12GetUserRankRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"{\n" +
	"\x13GetUserRankResponse\x12/\n" +
	"\n" +
	"user_score\x18\x01 \x01(\v2\x10.proto.UserScoreR\tuserScore\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x12\x1f\n" +
	"\vtotal_users\x18\x03 \x01(\x05R\n" +
	"totalUsers\"\x1f\n" +
	"\x1dRecalculateLeaderboardRequest\"\x8c\x01\n" +
	"\x1eRecalculateLeaderboardResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12'\n" +
	"\x0fusers_processed\x18\x02 \x01(\x05R\x0eusersProcessed\x12'\n" +
	"\x0fgames_evaluated\x18\x03 \x01(\x05R\x0egamesEvaluated2\x9f\x03\n" +
	"\x12LeaderboardService\x12M\n" +
	"\x0eGetLeaderboard\x12\x1c.proto.GetLeaderboardRequest\x1a\x1d.proto.GetLeaderboardResponse\x12G\n" +
	"\fGetUserStats\x12\x1a.proto.GetUserStatsRequest\x1a\x1b.proto.GetUserStatsResponse\x12D\n" +
	"\vGetTopUsers\x12\x19.proto.GetTopUsersRequest\x1a\x1a.proto.GetTopUsersResponse\x12D\n" +
	"\vGetUserRank\x12\x19.proto.GetUserRankRequest\x1a\x1a.proto.GetUserRankResponse\x12e\n" +
	"\x16RecalculateLeaderboard\x12$.proto.RecalculateLeaderboardRequest\x1a%.proto.RecalculateLeaderboardResponseB\x19Z\x17kickoff.com/proto;protob\x06proto3"

var (
	file_proto_leaderboard_service_proto_rawDescOnce sync.Once
	file_proto_leaderboard_service_proto_rawDescData []byte
)

func file_proto_leaderboard_service_proto_rawDescGZIP() []byte {
	file_proto_leaderboard_service_proto_rawDescOnce.Do(func() {
		file_proto_leaderboard_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_leaderboard_service_proto_rawDesc), len(file_proto_leaderboard_service_proto_rawDesc)))
	})
	return file_proto_leaderboard_service_proto_rawDescData
}

var file_proto_leaderboard_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_leaderboard_service_proto_goTypes = []any{
	(*UserScore)(nil),                      // 0: proto.UserScore
	(*PredictionDetail)(nil),               // 1: proto.PredictionDetail
	(*GetLeaderboardRequest)(nil),          // 2: proto.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil),         // 3: proto.GetLeaderboardResponse
	(*GetUserStatsRequest)(nil),            // 4: proto.GetUserStatsRequest
	(*GetUserStatsResponse)(nil),           // 5: proto.GetUserStatsResponse
	(*GetTopUsersRequest)(nil),             // 6: proto.GetTopUsersRequest
	(*GetTopUsersResponse)(nil),            // 7: proto.GetTopUsersResponse
	(*GetUserRankRequest)(nil),             // 8: proto.GetUserRankRequest
	(*GetUserRankResponse)(nil),            // 9: proto.GetUserRankResponse
	(*RecalculateLeaderboardRequest)(nil),  // 10: proto.RecalculateLeaderboardRequest
	(*RecalculateLeaderboardResponse)(nil), // 11: proto.RecalculateLeaderboardResponse
	(*timestamppb.Timestamp)(nil),          // 12: google.protobuf.Timestamp
}
var file_proto_leaderboard_service_proto_depIdxs = []int32{
	12, // 0: proto.PredictionDetail.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: proto.GetLeaderboardResponse.leaderboard:type_name -> proto.UserScore
	0,  // 2: proto.GetUserStatsResponse.user_stats:type_name -> proto.UserScore
	1,  // 3: proto.GetUserStatsResponse.predictions:type_name -> proto.PredictionDetail
	0,  // 4: proto.GetTopUsersResponse.top_users:type_name -> proto.UserScore
	0,  // 5: proto.GetUserRankResponse.user_score:type_name -> proto.UserScore
	2,  // 6: proto.LeaderboardService.GetLeaderboard:input_type -> proto.GetLeaderboardRequest
	4,  // 7: proto.LeaderboardService.GetUserStats:input_type -> proto.GetUserStatsRequest
	6,  // 8: proto.LeaderboardService.GetTopUsers:input_type -> proto.GetTopUsersRequest
	8,  // 9: proto.LeaderboardService.GetUserRank:input_type -> proto.GetUserRankRequest
	10, // 10: proto.LeaderboardService.RecalculateLeaderboard:input_type -> proto.RecalculateLeaderboardRequest
	3,  // 11: proto.LeaderboardService.GetLeaderboard:output_type -> proto.GetLeaderboardResponse
	5,  // 12: proto.LeaderboardService.GetUserStats:output_type -> proto.GetUserStatsResponse
	7,  // 13: proto.LeaderboardService.GetTopUsers:output_type -> proto.GetTopUsersResponse
	9,  // 14: proto.LeaderboardService.GetUserRank:output_type -> proto.GetUserRankResponse
	11, // 15: proto.LeaderboardService.RecalculateLeaderboard:output_type -> proto.RecalculateLeaderboardResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_leaderboard_service_proto_init() }
func file_proto_leaderboard_service_proto_init() {
	if File_proto_leaderboard_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_leaderboard_service_proto_rawDesc), len(file_proto_leaderboard_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_leaderboard_service_proto_goTypes,
		DependencyIndexes: file_proto_leaderboard_service_proto_depIdxs,
		MessageInfos:      file_proto_leaderboard_service_proto_msgTypes,
	}.Build()
	File_proto_leaderboard_service_proto = out.File
	file_proto_leaderboard_service_proto_goTypes = nil
	file_proto_leaderboard_service_proto_depIdxs = nil
}
